### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by olivroy**
# Summary

I noticed that many operations were performed more than once unnecessarily.

This PR aims to reduce this duplication.

It is not a perfect solution but it is the one that respects more the current structure.

I notice a speedup 690 ms -> 580 ms

# Related GitHub Issues and PRs

- Ref: #15

### CODE REVIEW

**Comment by rich-iannone** [comment]
Thank you! As with the other projects, please add yourself to the DESCRIPTION as your contributions are valuable!

**Comment by olivroy** [comment]
Thanks! I will stop it there for now. But I see about +30-50% performance improvement for the base `fmt_datetime()` from gt. Less operations are performed unnecessarily which greatly improves speed! As mentioned in a few places, it would be great to vectorize somehow, but the date-time formatting is quite comprehensive and we may simply want to branch out to simpler functions for the most trivial cases and keep `{bigD}` structure otherwise mostly untouched, except for the changes I propose here.

**Comment by olivroy** [comment]
Oops, just ran gt tests and discovered a slight regression. Will add test + fix soon

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Pull request merged**
